### ISSUE TITLE
helm deployment: rules-engine service omits kuiper-connections and kuipers-sources volumes

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-examples#158]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
EdgeX helm chart

### Description and Minimal Reproduction [**REQUIRED**]
The secure deployment of the helm chart omits the kuiper-connections and kuiper-sources volumes

From edgex-compose's `add-secure-mqtt-messagebus.yml`:

```
  rulesengine:
    entrypoint: [ "/edgex-init/kuiper_wait_install.sh" ]
    env_file:
      - common-sec-stage-gate.env
    volumes:
      - kuiper-sources:/kuiper/etc/sources:z
      - kuiper-connections:/kuiper/etc/connections:z
      - edgex-init:/edgex-init:ro,z
    depends_on:
      - security-bootstrapper
      - secretstore-setup
      - database
```

The above volumes are missing from the EdgeX helm chart.
