### ISSUE TITLE
helm deployment: Expose services on a per-service basis

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-examples#161]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
helm chart

### Description [**REQUIRED**]
The current helm chart has the following stanza
```yaml
expose:
  # Option value: ClusterIP/NodePort/LoadBalancer
  type: ClusterIP
```

This sets the service type for all "service" resources in the chart.

### Describe the solution you'd like
This setting is not granular enough.  It should be possible to set the service type on a per-service basis, with ClusterIP as the default for internal services, and NodePort as the default for externally-visible services such as consul and edgex-ui.

See also #160  which relates to hostPort exposure of EdgeX services.
