### ISSUE TITLE
Some questions about "send-command sample" application

### ISSUE THREAD

**Issue by Vieufoux** [edgexfoundry/edgex-examples#40]
Hi

I am referencing the architecture design in [send-command sample](https://github.com/edgexfoundry/edgex-examples/tree/master/application-services/custom/send-command) and trying to use aws iot sdk replace Azure IoT SDK. I have some questions about this example:
- How to deploy AWS Proxy Device Application(using AWS IoT SDK), do I need to start it as an application service in docker compose yaml file?
- If I have used the aws iot cert and key stored in the vault in the [aws export application](https://github.com/edgexfoundry/edgex-examples/tree/master/application-services/custom/aws-export) which is using for sending mqtt event to aws cloud, how can i **reuse** the same cert and key in AWS Proxy Device Application which is using for receive mqtt command from aws cloud.
- Is there any documentation shows how to store the cert and key in vault? I want to download aws iot cert and key from cloud and store in vault when device initialize.

**Comment by lenny-intel** [comment]
@Vieufoux , 

> * How to deploy AWS Proxy Device Application(using AWS IoT SDK), do I need to start it as an application service in docker compose yaml file?

@Vieufoux , you can add you app service to the appropriate Hanoi compose file found [here](https://github.com/edgexfoundry/edgex-compose/tree/hanoi). Use the `app-service-rules` service as a template. Be sure to remove the setting `EDGEX_PROFILE: rules-engine` as this is for app-service-configurable, not custom app services. If you plan on using the secure SecretStore (aka Vault) then you need `EDGEX_SECURITY_SECRET_STORE: "true" otherwise it will use the Insecure SecretStore (aka InsecureSecrets in configuration.toml). Are you wanting to use secure SecretStore?

**Comment by lenny-intel** [comment]
@Vieufoux here is the documentation on dealing with secrets in your custom application service.
https://docs.edgexfoundry.org/1.3/microservices/application/AdvancedTopics/#secrets 
One thing missing from the docs if the SetSecrets() API on the SDK
```
 StoreSecrets(path string, secrets map[string]string) error
```

This can be used to store the `aws iot cert and key from cloud` when the service first starts up. i.e. before you call MakeItRun()

**Comment by lenny-intel** [comment]
> * Is there any documentation shows how to store the cert and key in vault? I want to download aws iot cert and key from cloud and store in vault when device initialize.

@Vieufoux , here is the documentation for MQTT Trigger
https://docs.edgexfoundry.org/1.3/microservices/application/Triggers/#mqtt-trigger

Key here are thes MqttBroker configuration items:
```
    SecretPath = "mqtt-trigger" 
    AuthMode = "none" # Options are "none", "cacert" , "usernamepassword", "clientcert".
```
`SecretPath` is where in the SecretStore you have save the cert info. 
`Authmode` in your case I think would be `clientcert`
Not the when call `StoreSecrets` refenced in previous comment, use the same `Path` value and the key names for the map must be:
```
	AuthModeCert             = "clientcert"
	AuthModeCA               = "cacert"
	// Name of the keys to look for in secret provider
	MQTTSecretUsername   = "username"
	MQTTSecretPassword   = "password"
	MQTTSecretClientKey  = "clientkey"
	MQTTSecretClientKey  = "clientkey"
	MQTTSecretClientCert = AuthModeCert

``` 

Which are available as the constants:

**Comment by lenny-intel** [comment]
@Vieufoux , one last setup for using Secure SecretStore from app services. In the compose file you have to tell `secretstore-setup:` service to create a Secret Store for your service. This is done by add your service to the following environment variable, which takes a comma separated list of service names. You will need to add the environment varable

```
      ADD_SECRETSTORE_TOKENS: "service-name-1, service-name-2"
```
You will need to add this environment variable to `secretstore-setup's`  `environment` section.

Then you need to update your services SecretStore configuration to match the name you use in the environment variable.
```
[SecretStore]
  Host = 'localhost'
  Port = 8200
  Path = '/v1/secret/edgex/<your-service-name>/'
  Protocol = 'https'
  RootCaCertPath = '/tmp/edgex/secrets/ca/ca.pem'
  ServerName = 'localhost'
  TokenFile = '/tmp/edgex/secrets/<your-service-name>/secrets-token.json'
  AdditionalRetryAttempts = 10
  RetryWaitPeriod = "1s"

  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'
```

Finally, in the compose file your service must have the following in addition to what is there from `app-service-rules`:
```
    environment:
      ...
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_SERVERNAME: edgex-vault

    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/<your-service-name>:/tmp/edgex/secrets/<your-service-name>:ro,z

```

**Comment by Vieufoux** [comment]
Thanks a lot @lenny-intel , I didn’t notice that external MQTT Trigger function was added to hanoi. Since the sdk has this feature, I think I don’t need an AWS Proxy Device Application now. I will try it and feedback.

**Comment by Vieufoux** [comment]
Hi @lenny-intel , I want to run [edgex-secrets-example](https://github.com/edgexfoundry/edgex-examples/tree/master/application-services/custom/secrets) and i meet this error:

```
level=INFO ts=2021-04-13T09:18:13.853622999Z app=secrets-example source=sdk.go:358 msg="Starting secrets-example 0.0.0 "
level=INFO ts=2021-04-13T09:18:13.858023142Z app=secrets-example source=config.go:193 msg="Loaded configuration from /res/configuration.toml"
level=INFO ts=2021-04-13T09:18:13.859286371Z app=secrets-example source=variables.go:394 msg="Variables override of 'Clients.CoreData.Host' by environment variable: CLIENTS_COREDATA_HOST=edgex-core-data"
level=INFO ts=2021-04-13T09:18:13.859395005Z app=secrets-example source=variables.go:394 msg="Variables override of 'SecretStore.ServerName' by environment variable: SECRETSTORE_SERVERNAME=edgex-vault"
level=INFO ts=2021-04-13T09:18:13.859444435Z app=secrets-example source=variables.go:394 msg="Variables override of 'Registry.Host' by environment variable: REGISTRY_HOST=edgex-core-consul"
level=INFO ts=2021-04-13T09:18:13.859461561Z app=secrets-example source=variables.go:394 msg="Variables override of 'Service.Port' by environment variable: SERVICE_PORT=48095"
level=INFO ts=2021-04-13T09:18:13.859538619Z app=secrets-example source=variables.go:394 msg="Variables override of 'Service.Host' by environment variable: SERVICE_HOST=app-service-secrets-example"
level=INFO ts=2021-04-13T09:18:13.859554894Z app=secrets-example source=variables.go:394 msg="Variables override of 'SecretStore.Host' by environment variable: SECRETSTORE_HOST=edgex-vault"
level=INFO ts=2021-04-13T09:18:13.859808994Z app=secrets-example source=config.go:168 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/appservices/1.0/secrets-example"
level=INFO ts=2021-04-13T09:18:14.104887544Z app=secrets-example source=config.go:304 msg="Configuration has been pushed to into Configuration Provider (6 envVars overrides applied)"
level=ERROR ts=2021-04-13T09:18:14.104940245Z app=secrets-example source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2021-04-13T09:18:14.104965593Z app=secrets-example source=registry.go:80 msg="Using Registry (consul) from http://edgex-core-consul:8500"
level=INFO ts=2021-04-13T09:18:14.157030593Z app=secrets-example source=telemetry.go:79 msg="Starting CPU Usage Average loop"
level=INFO ts=2021-04-13T09:18:14.156699583Z app=secrets-example source=version.go:81 version=0.0.0 msg="Skipping version compatibility check for SDK Beta version or running in debugger"
level=INFO ts=2021-04-13T09:18:14.157586443Z app=secrets-example source=server.go:284 msg="Registering standard routes..."
level=INFO ts=2021-04-13T09:18:14.157728705Z app=secrets-example source=configupdates.go:51 msg="Waiting for App Service configuration updates..."
level=INFO ts=2021-04-13T09:18:14.15792942Z app=secrets-example source=controller.go:63 msg="Registering standard V2 routes..."
level=INFO ts=2021-04-13T09:18:14.158207701Z app=secrets-example source=sdk.go:438 msg="Service started in: 304.678267ms"
level=INFO ts=2021-04-13T09:18:14.158295037Z app=secrets-example source=main.go:49 msg="Filtering for devices [Random-Float-Device]"
level=INFO ts=2021-04-13T09:18:14.158335719Z app=secrets-example source=sdk.go:468 msg="HTTP trigger selected"
level=INFO ts=2021-04-13T09:18:14.158352451Z app=secrets-example source=rest.go:54 msg="Initializing HTTP Trigger"
level=INFO ts=2021-04-13T09:18:14.158450419Z app=secrets-example source=rest.go:58 msg="HTTP Trigger Initialized"
level=INFO ts=2021-04-13T09:18:14.158467159Z app=secrets-example source=sdk.go:186 msg="StoreAndForward disabled. Not running retry loop."
level=INFO ts=2021-04-13T09:18:14.158481271Z app=secrets-example source=sdk.go:189 msg="This is a sample Filter/XML Transform Application Service"
level=INFO ts=2021-04-13T09:18:14.158517223Z app=secrets-example source=server.go:359 msg="Starting HTTP Web Server on address :48095"
level=ERROR ts=2021-04-13T09:19:18.092164685Z app=secrets-example source=controller.go:146 msg="Storing secrets failed -> can't store secret(s) 'SecretProvider' is not properly initialized"
```

Here is my steps:

1. I am on hanoi branch

2. I add the environment varable `ADD_SECRETSTORE_TOKENS: secrets-example` to the `vault-worker` service in the `docker-compose-hanoi.yml` 

3. Then update the service configuration:

   ```yaml
   [SecretStore]
     Host = 'localhost'
     Port = 8200
     Path = '/v1/secret/edgex/secrets-example/'
     Protocol = 'https'
     RootCaCertPath = '/tmp/edgex/secrets/ca/ca.pem'
     ServerName = 'localhost'
     TokenFile = '/tmp/edgex/secrets/secrets-example/secrets-token.json'
     AdditionalRetryAttempts = 10
     RetryWaitPeriod = "1s"
   
     [SecretStore.Authentication]
     AuthType = 'X-Vault-Token'
   
   #[SecretStoreExclusive]
   #  Host = 'localhost'
   #  Port = 8200
   #  Path = '/v1/secret/edgex/secrets-example/'
   #  Protocol = 'https'
   #  RootCaCertPath = '/tmp/edgex/secrets/ca/ca.pem'
   #  ServerName = 'localhost'
   #  TokenFile = '/tmp/edgex/secrets/secrets-example/secrets-token.json'
   #  AdditionalRetryAttempts = 10
   #  RetryWaitPeriod = "1s"
   #
   #  [SecretStoreExclusive.Authentication]
   #  AuthType = 'X-Vault-Token'
   ```

4. make run

5. Verify that the following services are running:

   - edgex-secrets-setup
   - edgex-vault
   - edgex-vault-worker

6. Verify that the token `secrets-example` exist under `/tmp/edgex/secrets`

7. Create `secrets-example.yml` file

   ```yaml
   networks:
     edgex-network:
       driver: bridge
   services:
     app-service-secrets-example:
       container_name: app-service-secrets-example
       environment:
         CLIENTS_COMMAND_HOST: edgex-core-command
         CLIENTS_COREDATA_HOST: edgex-core-data
         CLIENTS_DATA_HOST: edgex-core-data
         CLIENTS_METADATA_HOST: edgex-core-metadata
         CLIENTS_NOTIFICATIONS_HOST: edgex-support-notifications
         CLIENTS_RULESENGINE_HOST: edgex-kuiper
         CLIENTS_SCHEDULER_HOST: edgex-support-scheduler
         CLIENTS_VIRTUALDEVICE_HOST: edgex-device-virtual
         DATABASES_PRIMARY_HOST: edgex-redis
         REGISTRY_HOST: edgex-core-consul
         SERVICE_HOST: app-service-secrets-example
         SERVICE_PORT: 48095
         EDGEX_SECURITY_SECRET_STORE: "true"
         SECRETSTORE_HOST: edgex-vault
         SECRETSTORE_SERVERNAME: edgex-vault
       volumes:
         - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
         - /tmp/edgex/secrets/secrets-example:/tmp/edgex/secrets/secrets-example:ro,z
       hostname: app-service-secrets-example
       image: edgexfoundry/docker-secrets-example:dev
       networks:
         edgex-network: {}
       ports:
         - 48095:48095/tcp
   
   version: '3.7'
   ```

8. Run the secrets example service:

   ```shell
   docker-compose -p edgex -f secrets-example.yml up -d
   ```

9. I invoke the api to create secrets http://<myip>:48095/api/v1/secrets and I and got the error above `level=ERROR ts=2021-04-13T09:19:18.092164685Z app=secrets-example source=controller.go:146 msg="Storing secrets failed -> can't store secret(s) 'SecretProvider' is not properly initialized"`
